### ISSUE TITLE
Undefined on properties.

### ISSUE THREAD

**Issue by clark-stevenson** [wight-airmash/ab-protocol#10]
If there is a preference on where to chat, let me know!

In many of the interfaces, if not all.  All properties are optionally undefined. 

The one I am looking at is [this server interface (link)](https://github.com/wight-airmash/ab-protocol/blob/e3260ec1f6574508995eba362a993a7359a9cc37/src/types/packets-server.ts#L722)

On the front end the firewallStatus seems to be a constant on the left, and now faces optional undefined properties on the right. 

So this code results in 4 errors because `firewallStatus.pos.x` can only be a number, whereas `command.posX` may be undefined.

```typescript
export const handleFirewall = (command: ServerPackets.GameFirewall) => {
    if (0 === command.status) {
        deinitMinimapAndFirewall();
    } else {
        firewallStatus.pos.x = command.posX;
        firewallStatus.radius = command.radius;
        firewallStatus.pos.y = command.posY;
        firewallStatus.speed = command.speed;
        popFirewall(firewallStatus.pos, firewallStatus.radius);
    }
};
```

This can be solved with casting as we are aware, but this still just lets `undefined` slip through. 

```typescript
export const handleFirewall = (command: ServerPackets.GameFirewall) => {
    if (0 === command.status) {
        deinitMinimapAndFirewall();
    } else {
        firewallStatus.pos.x = command.posX as number;
        firewallStatus.radius = command.radius as number;
        firewallStatus.pos.y = command.posY as number;
        firewallStatus.speed = command.speed as number;
        popFirewall(firewallStatus.pos, firewallStatus.radius);
    }
};
```

But I feel like the front end is expecting it to be there as there seems to be no checks in other calculations. 

In later code for example, the `firewallStatus.radius` could not be undefined.  It must always be a number. 

 
```typescript
export const update = (resizeMiniMap = false) => {
    if (GAME_TYPES.CTF === game.gameType && ctfGameState.flagBlue) {
        updateCtfFlagState(ctfGameState.flagBlue, resizeMiniMap);
        updateCtfFlagState(ctfGameState.flagRed, resizeMiniMap);
    }
    if (GAME_TYPES.BTR == game.gameType && minimapIsInitialized) {
        firewallStatus.radius += (firewallStatus.speed / 60) * game.timeFactor;
        popFirewall(firewallStatus.pos, firewallStatus.radius);
    }
};
```

**So my question is!**

Is `undefined` a possibility for each individual property (on your side?) or can the optional properties be removed so that `command.posX` is always a number, it CANNOT be undefined?

```typescript
export const handleFirewall = (command: ServerPackets.GameFirewall) => {
    if (0 === command.status) {
        deinitMinimapAndFirewall();
    } else {
        firewallStatus.pos.x = command.posX;
        firewallStatus.radius = command.radius;
        firewallStatus.pos.y = command.posY;
        firewallStatus.speed = command.speed;
        popFirewall(firewallStatus.pos, firewallStatus.radius);
    }
};
```

**Comment by wight-airmash** [comment]
In short: none of the properties are optional, in this case the types don't meet the actual requirements.

**Comment by clark-stevenson** [comment]
That's fair enough, thanks wight!

**Comment by clark-stevenson** [comment]
@wight-airmash 

Can you expand further?

If none of the properties are optional, why are they optional?   Because for example, I will copy and paste:

- `@airbattle\protocol\dist\types\packets-server.d.ts`

And just make them not optional and it resolves 1200+ errors in the type system on the front end.

**Comment by wight-airmash** [comment]
https://github.com/wight-airmash/ab-server ← here's an example of a project that uses this whole package without errors.
